# Generated by Django 4.1.5 on 2023-02-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_topics_course_topics_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='C:/videos'),
        ),
    ]
